### ISSUE TITLE
Require direct addressing for 'tell' commands

### ISSUE THREAD

**Issue by gunnbr** [gunnbr/GthxNetBot#12]
From the existing DB, phrases like "Tell you what, I'll do that for you!" or "Tell me you've heard of reprap" add tell requests. These common words "you" and "me" should be filtered out from triggering a tell request.

**Comment by Duckle29** [comment]
Maybe just require it to be prefixed with gthx like `gthx: tell dudebro that stuff is things` This way you're explicitly telling gthx that you want to relay a message, instead of just shouting into the irc void and hoping some bot takes note :P

**Comment by gunnbr** [comment]
Hmmm.... good point! I'm not sure why it isn't that way already. I think probably because gthx was originally written to behave exactly the same as kthx and kthx worked without being directly addressed. 

Fortunately it's trivial to change to only work when directly addressed.

**Comment by gunnbr** [comment]
Thanks for the suggestion, @Duckle29 . It's fixed to require direct addressing now!
