### ISSUE TITLE
"seen" is maybe a bit too eager

### ISSUE THREAD

**Issue by Duckle29** [gunnbr/GthxNetBot#16]
![image](https://user-images.githubusercontent.com/2756925/132957195-04051d48-75e7-4975-a362-2fb1b43a8aee.png)

**Comment by gunnbr** [comment]
Whoops! I'm in the middle of a bunch of other changes, so I'll throw a fix in for this as well. Thanks for the report, @Duckle29 !

**Comment by gunnbr** [comment]
Sorry, I got distracted by some bugs with the YouTube and Thingiverse refs that weren't working at all, so this ended up taking longer than expected. I have a fix for it now though.
